# Nginx configuration for template-server.home
#
# This configuration sets up a reverse proxy for the template-server.home domain,
# redirecting HTTP traffic to HTTPS and forwarding requests to the FastAPI server (http://localhost:8000 by default).
#
# Generate a self-signed SSL certificate:
#
# sudo openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout /etc/ssl/private/template-server.home.key \
# -out /etc/ssl/certs/template-server.home.crt -subj "/CN=template-server.home"   -addext "subjectAltName=DNS:template-server.home"
#
# To enable this configuration:
#
# 1. sudo cp template-server.home.conf /etc/nginx/sites-available/
# 2. sudo ln -s /etc/nginx/sites-available/template-server.home.conf /etc/nginx/sites-enabled/
# 3. sudo nginx -t
# 4. sudo systemctl reload nginx
#
# Ensure you add a local DNS record for template-server.home with the IP address of your server in your local DNS resolver.

server {
    listen 80;
    server_name template-server.home;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name template-server.home;

    ssl_certificate     /etc/ssl/certs/template-server.home.crt;
    ssl_certificate_key /etc/ssl/private/template-server.home.key;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
