name: Frontend
description: Runs frontend validation checks (type-checking, linting, formatting, testing) and uploads coverage reports.

runs:
  using: composite
  steps:
      - uses: ./.github/actions/setup/setup-node
        if: github.event.repository.name == 'python-template-server'
      - uses: javidahmed64592/python-template-server/.github/actions/setup/setup-node@main
        if: github.event.repository.name != 'python-template-server'

      - name: Run type checking
        run: |
          npm run type-check
        working-directory: ${{ github.event.repository.name }}-frontend
        shell: bash

      - name: Run linting
        run: |
          npm run lint
        working-directory: ${{ github.event.repository.name }}-frontend
        shell: bash

      - name: Run formatting check
        run: |
          npm run format
        working-directory: ${{ github.event.repository.name }}-frontend
        shell: bash

      - name: Run tests
        run: |
          npm run test:coverage
        working-directory: ${{ github.event.repository.name }}-frontend
        shell: bash

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v7
        with:
          name: frontend-coverage-report
          path: ${{ github.event.repository.name }}-frontend/coverage
