name: Generate Release Notes
description: Generates a release notes markdown file for a GitHub release.

inputs:
  version:
    description: Release version (without the v prefix)
    required: true

runs:
  using: composite
  steps:
    - name: Generate release notes
      id: generate
      run: |
        sed \
          -e 's|{{VERSION}}|${{ inputs.version }}|g' \
          -e 's|{{REPOSITORY}}|${{ github.repository }}|g' \
          -e 's|{{PACKAGE_NAME}}|${{ env.PACKAGE_NAME }}|g' \
          RELEASE-NOTES.md
      shell: bash
