name: Build and Start Services
description: Creates .env file from example and starts Docker Compose services.

inputs:
  wait-seconds:
    description: Seconds to wait for services to start
    required: false
    default: "5"

runs:
  using: composite
  steps:
    - name: Build and start services with docker compose
      run: |
        mv .env.example .env
        docker compose up --build -d
        sleep ${{ inputs.wait-seconds }}
      shell: bash
