name: Build and Start Services
description: Creates .env file from example and starts Docker Compose services.

inputs:
  wait-seconds:
    description: Seconds to wait for services to start
    required: false
    default: "5"
  build-args:
    description: Build arguments for Docker Compose
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Build and start services with docker compose
      run: |
        mv .env.example .env
        docker compose ${{ inputs.build-args }} up --build -d
        sleep ${{ inputs.wait-seconds }}
      shell: bash
