name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    outputs:
      frontend-exists: ${{ steps.check-frontend.outputs.exists }}
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup/check-frontend-exists
        if: github.event.repository.name == 'python-template-server'
        id: check-frontend_local
      - uses: javidahmed64592/python-template-server/.github/actions/setup/check-frontend-exists@main
        if: github.event.repository.name != 'python-template-server'
        id: check-frontend_remote
      - id: check-frontend
        run: echo "exists=${{ steps.check-frontend_local.outputs.exists || steps.check-frontend_remote.outputs.exists }}" >> $GITHUB_OUTPUT
        shell: bash

      - uses: ./.github/actions/build/build-frontend
        if: steps.check-frontend.outputs.exists == 'true' && github.event.repository.name == 'python-template-server'
      - uses: javidahmed64592/python-template-server/.github/actions/build/build-frontend@main
        if: steps.check-frontend.outputs.exists == 'true' && github.event.repository.name != 'python-template-server'

  build-wheel:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v6

      - name: Download frontend build
        if: needs.build-frontend.outputs.frontend-exists == 'true'
        uses: actions/download-artifact@v8
        with:
          name: ${{ github.event.repository.name }}-frontend-build
          path: static

      - uses: ./.github/actions/build/build-wheel
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/build/build-wheel@main
        if: github.event.repository.name != 'template-python'

  verify-structure:
    runs-on: ubuntu-latest
    needs: build-wheel
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/build/verify-structure
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/build/verify-structure@main
        if: github.event.repository.name != 'template-python'
