name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-pyproject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/ci/validate-pyproject
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/ci/validate-pyproject@main
        if: github.event.repository.name != 'template-python'

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/ci/ruff
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/ci/ruff@main
        if: github.event.repository.name != 'template-python'

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/ci/mypy
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/ci/mypy@main
        if: github.event.repository.name != 'template-python'

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/ci/pytest
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/ci/pytest@main
        if: github.event.repository.name != 'template-python'

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/ci/bandit
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/ci/bandit@main
        if: github.event.repository.name != 'template-python'

  pip-audit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/ci/pip-audit
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/ci/pip-audit@main
        if: github.event.repository.name != 'template-python'

  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/ci/version-check
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/ci/version-check@main
        if: github.event.repository.name != 'template-python'

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup/check-frontend-exists
        if: github.event.repository.name == 'python-template-server'
        id: check-frontend_local
      - uses: javidahmed64592/python-template-server/.github/actions/setup/check-frontend-exists@main
        if: github.event.repository.name != 'python-template-server'
        id: check-frontend_remote
      - id: check-frontend
        run: echo "exists=${{ steps.check-frontend_local.outputs.exists || steps.check-frontend_remote.outputs.exists }}" >> $GITHUB_OUTPUT
        shell: bash

      - uses: ./.github/actions/ci/frontend
        if: steps.check-frontend.outputs.exists == 'true' && github.event.repository.name == 'python-template-server'
      - uses: javidahmed64592/python-template-server/.github/actions/ci/frontend@main
        if: steps.check-frontend.outputs.exists == 'true' && github.event.repository.name != 'python-template-server'
